import { useState } from 'react'
import './App.css'
import { BrowserRouter, Route, Routes, Link } from "react-router-dom";

function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/index.html" element={<Index />} />
        <Route path="/lists" element={<Lists />} />
        <Route path="*" element={<Not_Found />} />
      </Routes>
    </BrowserRouter>
  );
}

// before accessing lists, get token
// use effect
// access token generated by flask when the user logs in
// plug in the username to generate token

function Index() {
  return (
    <>
      <h1>Login</h1>
      <div>
        <form method="POST" action="/create_account">
          <p>
            <label htmlFor="username">Username:</label>
            <input type="text" id="username" name="username" required />
          </p>
          <p>
            <label htmlFor="password">Password:</label>
            <input type="text" id="password" name="password" required />
          </p>
          <Link to="/lists"> <input type="submit" value="Create Account" name="submit" id="submit" /> </Link>
        </form>
      </div>
    </>
  );
}

function Lists() {

  return (
    <>
      <h1>User Lists</h1>
      <div>
        <p>Select a list to make a bracket for:</p>
        <select name="user_lists" id="user_lists">
          <option value="standard_list">Select a List</option>
        </select>
      </div>
    </>
  );
}

// function add_lists() {
  
// }

function Not_Found() {
  return (
    <>
      <h1>Page Not Found</h1>
      <div>
        <p>Did you meant to go to any of these pages?</p>
        <nav>
          <ul>
            <li>
              <Link to="/index">Login Page</Link>
            </li>
            <li>
              <Link to="/lists">List Page</Link>
            </li>
          </ul>
        </nav>
      </div>
    </>
  );
}

export default App